# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aux_ripp', '0005_auto_20180731_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_master',
            name='bid_id',
            field=models.CharField(default=b'', max_length=2500),
        ),
        migrations.AlterField(
            model_name='transaction_master',
            name='ledger_index',
            field=models.CharField(default=b'', max_length=2500),
        ),
    ]
