# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aux_ripp', '0006_auto_20180731_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address_master',
            old_name='enc_pk',
            new_name='enc_sk',
        ),
        migrations.RenameField(
            model_name='address_master',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='user_master',
            name='name',
        ),
        migrations.AddField(
            model_name='user_master',
            name='app_key',
            field=models.CharField(default=b'', max_length=500),
        ),
        migrations.AddField(
            model_name='user_master',
            name='app_secret',
            field=models.CharField(default=b'', max_length=500),
        ),
        migrations.AddField(
            model_name='user_master',
            name='notification_url',
            field=models.URLField(default=b'', max_length=500),
        ),
        migrations.AddField(
            model_name='user_master',
            name='user_name',
            field=models.CharField(default=b'', max_length=500),
        ),
    ]
