# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aux_ripp', '0007_auto_20180801_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_master',
            name='bid_id',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='transaction_master',
            name='ledger_index',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='app_key',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='app_secret',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='notification_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='user_name',
            field=models.CharField(max_length=500),
        ),
    ]
