# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aux_ripp', '0008_auto_20180801_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address_master',
            old_name='enc_sk',
            new_name='enc_master_seed',
        ),
        migrations.AddField(
            model_name='address_master',
            name='enc_master_key',
            field=models.CharField(default=b'', max_length=500),
        ),
        migrations.AddField(
            model_name='address_master',
            name='public_key',
            field=models.CharField(default=b'', max_length=500),
        ),
        migrations.AlterField(
            model_name='address_master',
            name='user_name',
            field=models.CharField(max_length=500),
        ),
    ]
