# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aux_ripp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address_master',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='address_master',
            name='is_multi_sig',
            field=models.BooleanField(default=False),
        ),
    ]
