# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aux_ripp', '0003_transaction_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_master',
            name='ledger_index',
            field=models.CharField(default=b'', max_length=2500),
        ),
        migrations.AddField(
            model_name='transaction_master',
            name='sequence',
            field=models.CharField(default=b'', max_length=2500),
        ),
    ]
