# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aux_ripp', '0004_auto_20180731_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_master',
            name='ledger_index',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='transaction_master',
            name='sequence',
            field=models.CharField(max_length=2500),
        ),
    ]
