# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-03 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=500)),
                ('token', models.CharField(max_length=500)),
                ('notification_url', models.URLField(max_length=500)),
                ('app_key', models.CharField(max_length=500)),
                ('app_secret', models.CharField(max_length=500)),
            ],
        ),
    ]
