# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-03 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_user_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_master',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
