# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-03 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_auto_20180803_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panel_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_user', models.CharField(max_length=100)),
                ('panel_user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
            ],
        ),
    ]
