# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-04 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_transaction_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('enc_sk', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('is_multi_sig', models.BooleanField(default=False)),
            ],
        ),
    ]
