# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_address_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuxRippAddressMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('enc_master_seed', models.CharField(max_length=500)),
                ('is_active', models.IntegerField()),
                ('is_multi_sig', models.IntegerField()),
                ('enc_master_key', models.CharField(max_length=500)),
                ('public_key', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'aux_ripp_address_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuxRippTransactionMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=2500)),
                ('to_address', models.CharField(max_length=2500)),
                ('amount', models.CharField(max_length=2500)),
                ('txid', models.CharField(max_length=2500)),
                ('created_at', models.DateTimeField()),
                ('ledger_index', models.CharField(max_length=2500)),
                ('sequence', models.CharField(max_length=2500)),
                ('bid_id', models.CharField(max_length=2500)),
            ],
            options={
                'db_table': 'aux_ripp_transaction_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuxRippUserMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('app_key', models.CharField(max_length=500)),
                ('app_secret', models.CharField(max_length=500)),
                ('notification_url', models.CharField(max_length=500)),
                ('user_name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'aux_ripp_user_master',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Address_Master',
        ),
        migrations.DeleteModel(
            name='Transaction_Master',
        ),
        migrations.DeleteModel(
            name='User_Master',
        ),
    ]
