# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-17 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_auto_20180808_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel_master',
            name='panel_user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
