# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=1000000)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=2500)),
                ('to_address', models.CharField(max_length=2500)),
                ('amount', models.CharField(max_length=2500)),
                ('txid', models.CharField(max_length=2500)),
                ('confirmation', models.IntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
